spring:
  application:
    name: activityservice
  data:
    mongodb:
        uri: mongodb://localhost:27017/fitness-activity
        database: fitness-activity

server:
    port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


